<a href="https://colab.research.google.com/github/eswaran-m13/colab/blob/main/DIMENSIONS_CREATING_AND_MANIPULATING_TENSORS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#1.A.DIMENSIONS CREATING AND MANIPULATING TENSORS
import tensorflow as tf
primes = tf.constant([53, 59, 61, 67, 71, 73], dtype=tf.int32)
print("primes:", primes)
ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)
just_beyond_primes = tf.add(primes, ones)
print("just_beyond_primes:", just_beyond_primes)
twos = tf.constant([2, 2, 2, 2, 2, 2],dtype=tf.int32)
primes_doubled = primes * twos
print("primes_doubled:", primes_doubled)
matrix = tf.constant([[9, 6, 3],[6, 4, 2]], dtype=tf.int32)
print(matrix)
print("\nvalue of matrix is:\n", some_matrix.numpy())

primes: tf.Tensor([53 59 61 67 71 73], shape=(6,), dtype=int32)
ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)
just_beyond_primes: tf.Tensor([54 60 62 68 72 74], shape=(6,), dtype=int32)
primes_doubled: tf.Tensor([106 118 122 134 142 146], shape=(6,), dtype=int32)
tf.Tensor(
[[9 6 3]
 [6 4 2]], shape=(2, 3), dtype=int32)

value of matrix is:
 [[9 6 3]
 [6 4 2]]
